/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesIdRouteImport } from './routes/matches.$id'
import { Route as CompetitionsIdRouteImport } from './routes/competitions.$id'

const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdRoute = MatchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MatchesRoute,
} as any)
const CompetitionsIdRoute = CompetitionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompetitionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRouteWithChildren
  '/matches': typeof MatchesRouteWithChildren
  '/competitions/$id': typeof CompetitionsIdRoute
  '/matches/$id': typeof MatchesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRouteWithChildren
  '/matches': typeof MatchesRouteWithChildren
  '/competitions/$id': typeof CompetitionsIdRoute
  '/matches/$id': typeof MatchesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRouteWithChildren
  '/matches': typeof MatchesRouteWithChildren
  '/competitions/$id': typeof CompetitionsIdRoute
  '/matches/$id': typeof MatchesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/competitions'
    | '/matches'
    | '/competitions/$id'
    | '/matches/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/competitions' | '/matches' | '/competitions/$id' | '/matches/$id'
  id:
    | '__root__'
    | '/'
    | '/competitions'
    | '/matches'
    | '/competitions/$id'
    | '/matches/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompetitionsRoute: typeof CompetitionsRouteWithChildren
  MatchesRoute: typeof MatchesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id': {
      id: '/matches/$id'
      path: '/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof MatchesIdRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/competitions/$id': {
      id: '/competitions/$id'
      path: '/$id'
      fullPath: '/competitions/$id'
      preLoaderRoute: typeof CompetitionsIdRouteImport
      parentRoute: typeof CompetitionsRoute
    }
  }
}

interface CompetitionsRouteChildren {
  CompetitionsIdRoute: typeof CompetitionsIdRoute
}

const CompetitionsRouteChildren: CompetitionsRouteChildren = {
  CompetitionsIdRoute: CompetitionsIdRoute,
}

const CompetitionsRouteWithChildren = CompetitionsRoute._addFileChildren(
  CompetitionsRouteChildren,
)

interface MatchesRouteChildren {
  MatchesIdRoute: typeof MatchesIdRoute
}

const MatchesRouteChildren: MatchesRouteChildren = {
  MatchesIdRoute: MatchesIdRoute,
}

const MatchesRouteWithChildren =
  MatchesRoute._addFileChildren(MatchesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompetitionsRoute: CompetitionsRouteWithChildren,
  MatchesRoute: MatchesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
